# ip_cam_pipeline.yaml
pipeline: >
  rtspsrc location="rtsp://admin:226419@10.37.1.226:554/live2.sdp" latency=200 ! 
  rtph264depay ! 
  video/x-raw, width=1280, height=720, framerate=7/1 !
  nvvideoconvert ! 
  video/x-raw(memory:NVMM), format=NV12 ! 
  mux.sink_0 nvstreammux name=mux batch-size=1 width=1280 height=720 ! 
  nvinfer name=pgie_0 config-file-path=pgie_yolov11_config.txt ! 
  nvtracker ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=tracker_config.txt ! 
  nvdsosd name=nvdsosd_0 ! 
  nvvideoconvert ! 
  video/x-raw, format=BGRx ! 
  videoconvert ! 
  jpegenc !
  appsink name=ros_sink emit-signals=true sync=false
